Feature historico component
MikaelMedeiros/orc-tatu pull request #9
Opened 2024-02-20 02:33 UTC by rafaelbarros2

2024-02-20 03:06 UTC, MikaelMedeiros requested changes
Não posso aprovar sem antes resolver os problemas apontados, pois isso irá para branch de dev, que é nosso ambiente de homologação. Inclusive, é até bom eu mudar o nome da branch para hml ou hom.

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/account/auth.interceptor.ts
>      console.log('Request URL: ' + req.url);
Remover console.log

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/app.module.routing.ts
> +         //canActivate: [authGuard]
Ativar guardião da rota

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/calculadora/calculadora.component.ts
> +      { name: 'Fineline', value: 'FINELINE' },
Corrigir todos os enums

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/historic/service/agendar.service.ts
> +    console.log('arou')
remover console.log

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/calculadora/calculadora.component.ts
>      this.historicService.saveOnBudgetHistory(budget).subscribe((data: any) => console.log('Deu bom!', data))
Remover console.log e adicionar next, error para mostrar um toast message: https://primeng.org/toast

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/historic/historic.component.ts
> +      .subscribe((data: any) => console.log('Deu bom!', data));
Remover console.log e adicionar toast message: https://primeng.org/toast

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/historic/historic.component.ts
> +  confirm1(event: Event, budget: BudgetHistory) {
renomear nome do metodo apenas para "confirm"

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/historic/historic.component.ts
> +          life: 300000,
Diminuir o tempo de vida do toast para 3segundos:  3000

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/historic/modal-agendamento/modal-agendamento.component.css
> +.label-radio {
remover css e utilizar o primeflex: https://primeflex.org/gridsystem
ou algum outra de preferência, tem vários que ajudam a organizar os items na tela.

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/historic/modal-agendamento/modal-agendamento.component.ts
> +    console.log(this.tipoTatoo)
Remover console.log

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/login/service/auth.service.ts
>            console.log(this.user)
remover console.log

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/principal/home/home.component.css
> +.align-content-start{
Utilizar primeflex para organizar os itens na tela: 
https://primeflex.org/alignitems

2024-02-20 03:06 UTC, MikaelMedeiros commented on src/app/principal/home/home.component.ts
> +           console.log(2)
remover console.log

2024-02-21 23:35 UTC, rafaelbarros2 commented on src/app/historic/modal-agendamento/modal-agendamento.component.css
> +.label-radio {
não obrigado

2024-02-22 00:05 UTC, rafaelbarros2 commented on src/app/principal/home/home.component.css
> +.align-content-start{
resolvido

2024-02-22 00:05 UTC, rafaelbarros2 commented on src/app/app.module.routing.ts
> +         //canActivate: [authGuard]
finalizado

2024-02-22 00:55 UTC, MikaelMedeiros commented on src/app/historic/modal-agendamento/modal-agendamento.component.css
> +.label-radio {
Suave, vamos deixar para uma próxima feature.

2024-02-22 00:56 UTC, MikaelMedeiros approved these changes

2024-02-22 00:56 UTC, merged